### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by inando** [hybridgroup/cppp-io#4]
Wouldn't it be a good idea to support locations for devices?
This makes it possible to group devices (and commands for those devices)

Example:

```
// GET /api/robots/TestBot/devices
{
  "devices": [
    {
      "name": "ping",
      "driver": "Ping",
      "connection": "loopback",
      "commands": ["ping"],
      "events": ["ping"],
      "location": "Room 2",      //<-- NEW
      "details": {
        "pin": "13",
        "test": "abc"
      }
    }
  ]
}

// GET /api/locations
{
    locations: ["Room 1", "Room 2"]
}

// GET /api/robots/:robot/locations/:location/devices
```

**Comment by inando** [comment]
Or maybe just an option to group/tag commands and get a command list from that group/tag.

**Comment by deadprogram** [comment]
This is something you could just add as Robot-level command right now in both Cylon.js and Gobot. I'm not sure that it requires extending the basic spec itself. Furthermore, wouldn't most location-based data apply more to Robots than Devices?

**Comment by inando** [comment]
I guess you are correct. I want to use it for home automation. I have one robot (a plc) and devices in different rooms. But I can start from these specs and extend them with what I need. Thanks!
